# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test

      # Build and push docker image
      - setup_remote_docker

      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          docker build -t gimc/personal:main .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push gimc/personal:main

      # Trigger container reload on server
      - add_ssh_keys:
          fingerprints:
            - "5c:23:fb:6f:bd:73:11:fd:45:b0:97:91:ff:59:f1:49"

      - deploy:
          name: Deploy
          command: ssh ubuntu@gimc.me "./scripts/deploy-main-prod.sh"
